
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Footer from "./component/Footer"
import Scrolltotopbtn from "./component/Scrolltotopbtn";
import Navbar from "./component/Navbar";
import Top from "./component/Top"
import HeroNavbar from "./component/HeroNavbar";



const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Buildpro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${montserrat.variable} antialiased`}>
      <body className="">
        <Navbar bgc="#393939"/>
        {children}
       <Scrolltotopbtn/>
        <Footer/>
        </body>
    </html>
  );
}
